version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    container_name: dm_pg
    networks:
      - my-network
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dm_password
      - POSTGRES_USER=dm_user
      - POSTGRES_DB=dm_backend
